default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  host: localhost
  pool: 5
  username: ubuntu
  password: hello

development:
  <<: *default
  database: lol_app_development

test:
  <<: *default
  database: lol_app_test

production:
  <<: *default
  database: lol_app_production